services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    
  PM\PlentyMarketsBundle\DocumentRepository\AccessTokenRepository: ~
  PM\PlentyMarketsBundle\DocumentRepository\ApiHitsRepository: ~
  PM\PlentyMarketsBundle\DocumentRepository\ApiLockRepository: ~
  PM\PlentyMarketsBundle\DocumentRepository\LimitHistoryRepository: ~

  PM\PlentyMarketsBundle\Services\Twig\AccountsTwigExtension:
    tags: [ { name: twig.extension } ]

  PM\PlentyMarketsBundle\Services\Twig\ApiTwigExtension:
    arguments:
      $apiLockRepository: '@PM\PlentyMarketsBundle\DocumentRepository\ApiLockRepository'

  jms_serializer.serialized_name_annotation_strategy:
    class: JMS\Serializer\Naming\SerializedNameAnnotationStrategy
    arguments:
      - '@jms_serializer.identical_property_naming_strategy'

  PM\PlentyMarketsBundle\Services\RestfulService:
    arguments:
      $accessTokenRepository: '@PM\PlentyMarketsBundle\DocumentRepository\AccessTokenRepository'
      $apiHitsRepository: '@PM\PlentyMarketsBundle\DocumentRepository\ApiHitsRepository'
      $apiLockRepository: '@PM\PlentyMarketsBundle\DocumentRepository\ApiLockRepository'
      $limitHistoryRepository: '@PM\PlentyMarketsBundle\DocumentRepository\LimitHistoryRepository'
      $serializer: '@jms_serializer.serializer'
      $objectManager: '@Doctrine\ODM\MongoDB\DocumentManager'
      $logger: '@logger'
      $parameterGuzzleVerifySsl: '%pm__plenty_market.configuration.guzzle.verify_ssl%'