<?php

namespace PM\PlentyMarketsBundle\Repository;

use DateTime;
use Doctrine\ORM\EntityRepository;
use PM\PlentyMarketsBundle\Entity\LimitHistory;

/**
 * LimitHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LimitHistoryRepository extends EntityRepository
{
    /**
     * Find Current
     *
     * @param string $apiId
     *
     * @return LimitHistory|null
     */
    public function findCurrent($apiId, $path)
    {
        $result = $this->findBy(
            [
                'api'  => $apiId,
                'path' => $path,
                'day'  => new DateTime(),
            ],
            null,
            1
        );

        if (0 === count($result)) {
            return null;
        }

        return reset($result);
    }
}
