<?php

namespace PM\PlentyMarketsBundle\DocumentRepository;

use Doctrine\Bundle\MongoDBBundle\Repository\ServiceDocumentRepository;
use Doctrine\Bundle\MongoDBBundle\ManagerRegistry;
use PM\PlentyMarketsBundle\Component\Interfaces\ApiHitsRepositoryInterface;
use PM\PlentyMarketsBundle\Component\Model\ApiHitsStatisticModel;
use PM\PlentyMarketsBundle\Document\ApiHits;

/**
 * ApiHitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiHitsRepository extends ServiceDocumentRepository implements ApiHitsRepositoryInterface
{
    /**
     * ApiHitsRepository constructor.
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ApiHits::class);
    }

    /**
     * Find Current
     *
     * @param string $apiId
     *
     * @return null|object|ApiHits
     */
    public function findCurrent($apiId)
    {
        return $this->findOneBy(
            [
                'apiId' => $apiId,
                'day' => new \DateTime(),
            ]
        );
    }

    //TODO: removed functionality rebuild for mongo
}
